In [3]:
import numpy as np

In [43]:
arr1 = list(range(100000))


In [44]:
arr2 = np.arange(10000)


In [45]:
%timeit sum(arr1)

2.68 ms ± 348 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
%timeit np.sum(arr2)

14.4 µs ± 395 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [33]:
a = np.array([-1, 0, 1, 100], dtype='int8')
a

array([ -1,   0,   1, 100], dtype=int8)

In [34]:
a ** 100

array([1, 0, 1, 0], dtype=int8)

In [35]:
b = a.astype('float32')
b

array([ -1.,   0.,   1., 100.], dtype=float32)

In [47]:
np.zeros((3, 4), dtype='int8')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [48]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
np.empty((4, 5))

array([[1.20443074e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.89146047e-307],
       [5.30276956e+180, 5.05117710e-038, 4.57752921e-071,
        3.85911877e-086, 3.35910091e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 2.19284356e-076],
       [5.22304403e-037, 4.03821203e-037, 3.11088275e+179,
        7.48930798e-144, 1.50008929e+248]])

In [50]:
a

array([ -1,   0,   1, 100], dtype=int8)

In [51]:
a[0]

-1

In [52]:
a[-1]

100

In [53]:
a[0:2]

array([-1,  0], dtype=int8)

In [54]:
a[1:3]

array([0, 1], dtype=int8)

In [55]:
a[::2]

array([-1,  1], dtype=int8)

In [56]:
a[-1] = 5
a

array([-1,  0,  1,  5], dtype=int8)

In [61]:
b = np.arange(12).reshape(4, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
b[:, 1:3]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [65]:
b[1:3, -1]

array([5, 8])

In [67]:
c = np.arange(24).reshape(2, 3, 4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [68]:
c[1, 1, 1]

17

In [69]:
c[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [73]:
d = np.arange(25).reshape(5, 5)
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [75]:
d[:, 1:4:2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [82]:
d[1:4:2, 2:]

array([[ 7,  8,  9],
       [17, 18, 19]])

In [84]:
d[4, :]

array([20, 21, 22, 23, 24])

In [85]:
len(d[0])

5

In [87]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [90]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [91]:
arr2 = arr.reshape(6, 4)
arr2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [92]:
arr3 = arr[1:15]
arr3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [93]:
arr4 = arr[arr > 15]
arr4

array([16, 17, 18, 19, 20, 21, 22, 23])

In [94]:
arr4.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [95]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [96]:
b = np.array([10, 20, 30, 40])
b

array([10, 20, 30, 40])

In [97]:
a + b

array([10, 21, 32, 43])

In [98]:
b - a

array([10, 19, 28, 37])

In [99]:
a * 2

array([0, 2, 4, 6])

In [102]:
a ** 2

array([0, 1, 4, 9], dtype=int32)

In [103]:
a * b

array([  0,  20,  60, 120])

In [104]:
b < 30

array([ True,  True, False, False])

In [105]:
b[b < 30]

array([10, 20])

In [106]:
a.dot(b)

200

In [107]:
A = np.array([[1, 1], [0, 1]])
A

array([[1, 1],
       [0, 1]])

In [109]:
B = np.array([[2, 0], [3, 4]])
B

array([[2, 0],
       [3, 4]])

In [111]:
A.shape

(2, 2)

In [112]:
B.shape

(2, 2)

In [113]:
A * B

array([[2, 0],
       [0, 4]])

In [114]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [116]:
A + B

array([[3, 1],
       [3, 5]])

In [117]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
b = a.reshape(2, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [121]:
c = a.reshape(4, -1)
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [122]:
d = a.reshape(-1, 2)
d

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [126]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [127]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [129]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [132]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [135]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [141]:
# np.array(list(range(10)))
# np.arange(10)

In [142]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [148]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [147]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [150]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [152]:
a[2:, 1:]

array([[ 7,  8],
       [10, 11]])

In [157]:
sum(a[:,1])

22

In [158]:
sum(a)

array([18, 22, 26])

In [162]:
a = np.arange(100)
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [168]:
b = a.reshape(10, 10)

In [2]:
import numpy as np

In [4]:
np.arange(10, 20).reshape(5, 2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [5]:
np.array([2, 6, 100, -1])

array([  2,   6, 100,  -1])

In [7]:
a = np.arange(12).reshape(3, 4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.sum(a)

66

In [10]:
np.sum(a, axis=0)

array([12, 15, 18, 21])

In [11]:
np.sum(a, axis=1)

array([ 6, 22, 38])

In [12]:
np.max(a)

11

In [14]:
np.max(a, axis=0)

array([ 8,  9, 10, 11])

In [15]:
np.max(a, axis=1)

array([ 3,  7, 11])

In [16]:
np.std(a)

3.452052529534663

In [17]:
np.mean(a)

5.5

In [18]:
np.median(a)

5.5

In [19]:
np.median(a, axis=0)

array([4., 5., 6., 7.])

In [20]:
np.linspace(1, 5, 5)

array([1., 2., 3., 4., 5.])

In [21]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [22]:
np.linspace(1, 5, 9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [24]:
# Random

In [25]:
np.random.rand(5)

array([0.67740398, 0.40441582, 0.39798441, 0.9452548 , 0.93736002])

In [26]:
np.random.rand()

0.5213074531023896

In [27]:
np.random.rand(4, 5)

array([[0.56679335, 0.13500429, 0.6307989 , 0.2165808 , 0.64280474],
       [0.4449635 , 0.4027936 , 0.0904889 , 0.95249507, 0.47169894],
       [0.94913968, 0.15431561, 0.78212131, 0.63965302, 0.68829881],
       [0.4628749 , 0.00132656, 0.67926664, 0.82524599, 0.9081869 ]])

In [28]:
np.random.randint(50, 60, 10)

array([51, 50, 55, 55, 52, 54, 50, 57, 59, 57])

In [32]:
# np.random.seed(100)
np.random.rand(4)

array([0.00471886, 0.12156912, 0.67074908, 0.82585276])

In [34]:
r = np.random.rand(4, 4)
r

array([[0.17541045, 0.37283205, 0.00568851, 0.25242635],
       [0.79566251, 0.01525497, 0.59884338, 0.60380454],
       [0.10514769, 0.38194344, 0.03647606, 0.89041156],
       [0.98092086, 0.05994199, 0.89054594, 0.5769015 ]])

In [36]:
r = r.flatten()
r.sort()
r

array([0.00568851, 0.01525497, 0.03647606, 0.05994199, 0.10514769,
       0.17541045, 0.25242635, 0.37283205, 0.38194344, 0.5769015 ,
       0.59884338, 0.60380454, 0.79566251, 0.89041156, 0.89054594,
       0.98092086])

In [41]:
mu = 5
sigma = 1
n = np.random.normal(mu, sigma, 100)
n

array([5.95295943, 4.01663736, 3.90544281, 4.75865125, 4.40488616,
       4.01718811, 5.08822993, 4.39724063, 6.12555545, 5.9270533 ,
       2.73084301, 4.65182936, 4.8359746 , 6.21658059, 4.3731461 ,
       4.72506019, 6.14745744, 6.15996897, 5.70218451, 3.71609519,
       6.52230777, 4.82003668, 4.62385263, 5.46034921, 6.45542146,
       5.24150689, 4.96233333, 5.83153303, 7.29936947, 4.06039756,
       5.11182258, 7.53943203, 5.40359842, 3.11516561, 6.27745203,
       4.55441174, 3.72968196, 5.63550117, 4.70156433, 4.59771008,
       4.46335957, 5.8231244 , 5.0251919 , 6.51753613, 5.36961115,
       4.51936784, 6.04233274, 6.09887599, 2.86708963, 5.75920433,
       4.71481913, 5.48041141, 5.46800069, 7.70900195, 7.01908612,
       5.74740342, 4.41029141, 4.18657518, 4.82310314, 5.5070475 ,
       4.73322184, 4.14393798, 6.55931486, 3.90731114, 5.7580425 ,
       3.80056003, 5.17637048, 4.12426916, 5.11760846, 4.04183166,
       3.11888535, 5.18234273, 4.45150772, 4.94736503, 8.17339

In [42]:
np.mean(n)

5.2250492215609485

In [43]:
np.std(n)

1.0989510347205453